apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: enterprise.splunk.com/v3
kind: Standalone
metadata:
  namespace: test
  name: test
spec:
  replicas: 1
  image: ghcr.io/marcusschiesser/splunk-gitops:main
  imagePullPolicy: Always
  etcVolumeStorageConfig:
    ephemeralStorage: true
  varVolumeStorageConfig:
    storageClassName: gp2
    storageCapacity: 100Gi
  extraEnv:
    - name: SPLUNK_START_ARGS
      value: "--accept-license"
    - name: SPLUNK_PASSWORD
      value: "mysplunkpassword"
